<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query'
import { ElDialog, ElMessage } from 'element-plus'
import { useRoute } from 'vue-router'
import { charactersApi } from '@/api/endpoints/assets'
import type { CharacterResponse, LifeStatus } from '@/api/types'
import EmptyState from '@/components/base/EmptyState.vue'
import ErrorState from '@/components/base/ErrorState.vue'
import LoadingState from '@/components/base/LoadingState.vue'
import ProblemAlert from '@/components/base/ProblemAlert.vue'
import { queryKeys } from '@/queries/keys'

const route = useRoute(); const client = useQueryClient(); const projectId = computed(() => String(route.params.projectId ?? ''))
const query = useQuery({ queryKey: computed(() => queryKeys.characters(projectId.value)), queryFn: () => charactersApi.list(projectId.value) })
const open = ref(false); const editing = ref<CharacterResponse>();
const form = reactive({ name:'', aliases:'', role:'', description:'', personality:'', background:'', goals:'', appearance:'', notes:'', lifeStatus:'UNKNOWN' as LifeStatus, currentLocation:'', physicalCondition:'', emotionalState:'', abilities:'', inventoryNotes:'', stateNotes:'' })
const mutation = useMutation({ mutationFn: async () => {
  const nullable = (v:string) => v.trim() || null
  if (!editing.value) return charactersApi.create(projectId.value, { name:form.name.trim(), aliases:nullable(form.aliases), role:nullable(form.role), description:nullable(form.description), personality:nullable(form.personality), background:nullable(form.background), goals:nullable(form.goals), appearance:nullable(form.appearance), notes:nullable(form.notes), state:{ lifeStatus:form.lifeStatus, currentLocation:nullable(form.currentLocation), physicalCondition:nullable(form.physicalCondition), emotionalState:nullable(form.emotionalState), abilities:nullable(form.abilities), inventoryNotes:nullable(form.inventoryNotes), notes:nullable(form.stateNotes) } })
  const current = editing.value
  const updated = await charactersApi.update(current.id, { name:form.name.trim(), aliases:nullable(form.aliases), role:nullable(form.role), description:nullable(form.description), personality:nullable(form.personality), background:nullable(form.background), goals:nullable(form.goals), appearance:nullable(form.appearance), notes:nullable(form.notes), archived:current.archived, expectedVersion:current.version })
  await charactersApi.updateState(current.id, { lifeStatus:form.lifeStatus, currentLocation:nullable(form.currentLocation), physicalCondition:nullable(form.physicalCondition), emotionalState:nullable(form.emotionalState), abilities:nullable(form.abilities), inventoryNotes:nullable(form.inventoryNotes), notes:nullable(form.stateNotes), expectedVersion:current.state.version })
  return updated
}, onSuccess: async () => { await client.invalidateQueries({queryKey:queryKeys.characters(projectId.value)}); open.value=false; ElMessage.success('人物卡已保存') } })
function show(item?:CharacterResponse){ editing.value=item; Object.assign(form, item ? { name:item.name, aliases:item.aliases??'', role:item.role??'', description:item.description??'', personality:item.personality??'', background:item.background??'', goals:item.goals??'', appearance:item.appearance??'', notes:item.notes??'', lifeStatus:item.state.lifeStatus??'UNKNOWN', currentLocation:item.state.currentLocation??'', physicalCondition:item.state.physicalCondition??'', emotionalState:item.state.emotionalState??'', abilities:item.state.abilities??'', inventoryNotes:item.state.inventoryNotes??'', stateNotes:item.state.notes??'' } : { name:'',aliases:'',role:'',description:'',personality:'',background:'',goals:'',appearance:'',notes:'',lifeStatus:'UNKNOWN',currentLocation:'',physicalCondition:'',emotionalState:'',abilities:'',inventoryNotes:'',stateNotes:'' }); open.value=true }
async function save(){ try{ await mutation.mutateAsync() }catch{/* rendered */} }
</script>
<template><main class="page-container"><header class="page-header"><div><p class="eyebrow">Characters</p><h1 tabindex="-1">人物</h1><p>从空白人物卡开始，人物信息与当前状态分别按真实版本保存。</p></div><button class="sw-button sw-button--primary" @click="show()">新建人物</button></header>
<LoadingState v-if="query.isPending.value"/><ErrorState v-else-if="query.isError.value" :error="query.error.value" @retry="query.refetch()"/><EmptyState v-else-if="!query.data.value?.length" title="还没有人物" description="创建空白人物卡后逐字段维护。"><button class="sw-button sw-button--primary" @click="show()">创建人物</button></EmptyState>
<section v-else class="asset-grid"><article v-for="item in query.data.value" :key="item.id" class="asset-card"><div class="asset-card-heading"><div><span class="asset-type">{{ item.role || '未设置角色' }}</span><h2>{{ item.name }}</h2></div><span class="status-pill">{{ item.state.lifeStatus || 'UNKNOWN' }}</span></div><p>{{ item.description || '尚未填写人物描述。' }}</p><dl class="compact-details"><div><dt>别名</dt><dd>{{ item.aliases || '-' }}</dd></div><div><dt>当前位置</dt><dd>{{ item.state.currentLocation || '-' }}</dd></div></dl><div class="asset-actions"><button @click="show(item)">编辑人物与状态</button></div></article></section>
<ElDialog v-model="open" :title="editing ? '编辑人物' : '新建人物'" width="min(760px,94vw)"><ProblemAlert v-if="mutation.isError.value" :error="mutation.error.value"/><form id="character-form" class="sw-form two-column-form" @submit.prevent="save"><label class="form-field"><span>姓名</span><input v-model="form.name" maxlength="120" required/></label><label class="form-field"><span>角色</span><input v-model="form.role" maxlength="80"/></label><label class="form-field"><span>别名</span><input v-model="form.aliases" maxlength="500"/></label><label class="form-field"><span>生命状态</span><select v-model="form.lifeStatus"><option>UNKNOWN</option><option>ALIVE</option><option>DEAD</option></select></label><label class="form-field form-field--full"><span>描述</span><textarea v-model="form.description" rows="3" maxlength="20000"/></label><label class="form-field"><span>性格</span><textarea v-model="form.personality" rows="3"/></label><label class="form-field"><span>背景</span><textarea v-model="form.background" rows="3"/></label><label class="form-field"><span>目标</span><textarea v-model="form.goals" rows="3"/></label><label class="form-field"><span>外貌</span><textarea v-model="form.appearance" rows="3"/></label><label class="form-field"><span>当前位置</span><input v-model="form.currentLocation" maxlength="200"/></label><label class="form-field"><span>情绪状态</span><input v-model="form.emotionalState" maxlength="5000"/></label><label class="form-field"><span>身体状态</span><textarea v-model="form.physicalCondition" rows="2"/></label><label class="form-field"><span>能力</span><textarea v-model="form.abilities" rows="2"/></label><label class="form-field"><span>随身物品</span><textarea v-model="form.inventoryNotes" rows="2"/></label><label class="form-field"><span>状态备注</span><textarea v-model="form.stateNotes" rows="2"/></label></form><template #footer><button class="sw-button sw-button--secondary" @click="open=false">取消</button><button class="sw-button sw-button--primary" form="character-form" :disabled="mutation.isPending.value">保存</button></template></ElDialog></main></template>
