<script setup lang="ts">
import { computed, reactive } from 'vue'
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query'
import { ElMessage } from 'element-plus'
import { useRoute } from 'vue-router'
import { foreshadowsApi } from '@/api/endpoints/v15'
import { chaptersApi } from '@/api/endpoints/assets'
import EmptyState from '@/components/base/EmptyState.vue'
import ErrorState from '@/components/base/ErrorState.vue'
import LoadingState from '@/components/base/LoadingState.vue'
import ProblemAlert from '@/components/base/ProblemAlert.vue'
const route=useRoute();const client=useQueryClient();const projectId=computed(()=>String(route.params.projectId??''));const key=computed(()=>['foreshadows',projectId.value]);const query=useQuery({queryKey:key,queryFn:()=>foreshadowsApi.list(projectId.value)});const chapters=useQuery({queryKey:computed(()=>['chapters',projectId.value]),queryFn:()=>chaptersApi.list(projectId.value)});const resolutions=reactive<Record<string,string>>({});const form=reactive({title:'',description:'',targetChapterNo:undefined as number|undefined,notes:''});const create=useMutation({mutationFn:()=>foreshadowsApi.create(projectId.value,{title:form.title,description:form.description||null,plantedChapterId:null,targetChapterNo:form.targetChapterNo??null,notes:form.notes||null}),onSuccess:async()=>{Object.assign(form,{title:'',description:'',targetChapterNo:undefined,notes:''});await client.invalidateQueries({queryKey:key.value});ElMessage.success('伏笔已创建')}});const transition=useMutation({mutationFn:({id,version,status,resolvedChapterId=null}:{id:string;version:number;status:string;resolvedChapterId?:string|null|undefined})=>foreshadowsApi.transition(id,{expectedVersion:version,status,resolvedChapterId}),onSuccess:async()=>client.invalidateQueries({queryKey:key.value})})
</script>
<template><main class="page-container"><header class="page-header"><div><p class="eyebrow">Foreshadow ledger</p><h1 tabindex="-1">伏笔台账</h1><p>显式记录计划、埋设、推进与回收状态，不根据正文自动猜测生命周期。</p></div></header><section class="v15-panel"><h2>登记伏笔</h2><ProblemAlert v-if="create.isError.value" :error="create.error.value"/><form class="sw-form" @submit.prevent="create.mutate()"><div class="form-row"><label class="form-field"><span>标题</span><input v-model="form.title" maxlength="160" required/></label><label class="form-field"><span>目标章节号</span><input v-model.number="form.targetChapterNo" type="number" min="1"/></label></div><label class="form-field"><span>说明</span><textarea v-model="form.description" rows="3"/></label><label class="form-field"><span>备注</span><textarea v-model="form.notes" rows="2"/></label><button class="sw-button sw-button--primary">创建</button></form></section><LoadingState v-if="query.isPending.value"/><ErrorState v-else-if="query.isError.value" :error="query.error.value" @retry="query.refetch()"/><EmptyState v-else-if="!query.data.value?.length" title="还没有伏笔" description="登记需要跨章跟踪的承诺。"/><section v-else class="asset-list"><article v-for="item in query.data.value" :key="item.id" class="asset-card"><div class="asset-card-heading"><div><span class="asset-type">目标第 {{ item.targetChapterNo ?? '-' }} 章</span><h2>{{ item.title }}</h2></div><span class="status-pill">{{ item.status }}</span></div><p>{{ item.description || '无说明' }}</p><div v-if="['PLANTED','ADVANCED'].includes(item.status)" class="form-row"><label class="form-field"><span>回收章节</span><select v-model="resolutions[item.id]"><option value="">选择章节</option><option v-for="chapter in chapters.data.value" :key="chapter.id" :value="chapter.id">第 {{ chapter.chapterNo }} 章 · {{ chapter.title }}</option></select></label><button class="sw-button sw-button--secondary" :disabled="!resolutions[item.id]" @click="transition.mutate({id:item.id,version:item.version,status:'RESOLVED',resolvedChapterId:resolutions[item.id]})">标记已回收</button></div><div class="asset-actions"><button v-if="item.status==='PLANNED'" @click="transition.mutate({id:item.id,version:item.version,status:'PLANTED'})">标记已埋设</button><button v-if="['PLANTED','ADVANCED'].includes(item.status)" @click="transition.mutate({id:item.id,version:item.version,status:'ADVANCED'})">推进一次</button><button v-if="!['RESOLVED','ABANDONED'].includes(item.status)" @click="transition.mutate({id:item.id,version:item.version,status:'ABANDONED'})">放弃</button></div></article></section></main></template>
