<script setup lang="ts">
import { computed, nextTick, reactive, ref } from 'vue'; import { useMutation,useQuery,useQueryClient } from '@tanstack/vue-query'; import { ElDialog,ElMessage } from 'element-plus'; import { useRoute } from 'vue-router'
import { outlinesApi } from '@/api/endpoints/assets'; import type { OutlineNodeType,OutlineResponse } from '@/api/types'; import EmptyState from '@/components/base/EmptyState.vue'; import ErrorState from '@/components/base/ErrorState.vue'; import LoadingState from '@/components/base/LoadingState.vue'; import ProblemAlert from '@/components/base/ProblemAlert.vue'; import { queryKeys } from '@/queries/keys'
const route=useRoute(),client=useQueryClient(),projectId=computed(()=>String(route.params.projectId??'')); const query=useQuery({queryKey:computed(()=>queryKeys.outlines(projectId.value)),queryFn:()=>outlinesApi.list(projectId.value)}); const sorted=computed(()=>[...(query.data.value??[])].sort((a,b)=>a.sequenceNo-b.sequenceNo)); const open=ref(false),editing=ref<OutlineResponse>(); const form=reactive({parentId:'',nodeType:'MASTER' as OutlineNodeType,title:'',summary:'',objective:'',sequenceNo:0}); const mutation=useMutation({mutationFn:()=>editing.value?outlinesApi.update(editing.value.id,{title:form.title.trim(),summary:form.summary.trim()||null,objective:form.objective.trim()||null,sequenceNo:Number(form.sequenceNo),expectedVersion:editing.value.version}):outlinesApi.create(projectId.value,{parentId:form.parentId||null,nodeType:form.nodeType,title:form.title.trim(),summary:form.summary.trim()||null,objective:form.objective.trim()||null,sequenceNo:Number(form.sequenceNo)}),onSuccess:async()=>{await client.invalidateQueries({queryKey:queryKeys.outlines(projectId.value)});open.value=false;ElMessage.success('大纲节点已保存')}})
function show(x?:OutlineResponse){editing.value=x;Object.assign(form,x?{parentId:x.parentId??'',nodeType:x.nodeType,title:x.title,summary:x.summary??'',objective:x.objective??'',sequenceNo:x.sequenceNo}:{parentId:'',nodeType:'MASTER',title:'',summary:'',objective:'',sequenceNo:sorted.value.length});open.value=true} async function save(){try{await mutation.mutateAsync()}catch{/*rendered*/}}
async function moveFocus(index:number,delta:number){await nextTick();const nodes=globalThis.document.querySelectorAll('[role="treeitem"]');(nodes[Math.max(0,Math.min(nodes.length-1,index+delta))] as {focus:()=>void}|undefined)?.focus()}
</script>
<template><main class="page-container"><header class="page-header"><div><p class="eyebrow">Outline</p><h1 tabindex="-1">大纲</h1><p>使用真实父节点、类型和顺序字段建立大纲树。</p></div><button class="sw-button sw-button--primary" @click="show()">新建节点</button></header><div class="capability-note">后端当前没有拆分、合并、移动或批量重排接口，因此不提供假拖拽。</div><LoadingState v-if="query.isPending.value"/><ErrorState v-else-if="query.isError.value" :error="query.error.value" @retry="query.refetch()"/><EmptyState v-else-if="!sorted.length" title="还没有大纲" description="先创建总纲或分卷。"><button class="sw-button sw-button--primary" @click="show()">创建节点</button></EmptyState><div v-else class="outline-tree" role="tree" aria-label="项目大纲"><button v-for="(x,index) in sorted" :key="x.id" role="treeitem" :aria-level="x.parentId?2:1" class="outline-node" :style="{marginInlineStart:x.parentId?'28px':'0'}" @click="show(x)" @keydown.down.prevent="moveFocus(index,1)" @keydown.up.prevent="moveFocus(index,-1)"><span class="asset-type">{{ x.nodeType }} · {{ x.sequenceNo }}</span><strong>{{ x.title }}</strong><small>{{ x.objective||x.summary||'未填写目标' }}</small></button></div>
<ElDialog v-model="open" :title="editing?'编辑大纲节点':'新建大纲节点'" width="min(620px,94vw)"><ProblemAlert v-if="mutation.isError.value" :error="mutation.error.value"/><form id="outline-form" class="sw-form" @submit.prevent="save"><label v-if="!editing" class="form-field"><span>节点类型</span><select v-model="form.nodeType"><option>MASTER</option><option>VOLUME</option><option>ARC</option><option>CHAPTER</option></select></label><label v-if="!editing" class="form-field"><span>父节点 UUID（可空）</span><input v-model="form.parentId"/></label><label class="form-field"><span>标题</span><input v-model="form.title" maxlength="160" required/></label><label class="form-field"><span>摘要</span><textarea v-model="form.summary" rows="4"/></label><label class="form-field"><span>目标</span><textarea v-model="form.objective" rows="4"/></label><label class="form-field"><span>顺序</span><input v-model.number="form.sequenceNo" type="number" min="0"/></label></form><template #footer><button class="sw-button sw-button--secondary" @click="open=false">取消</button><button class="sw-button sw-button--primary" form="outline-form">保存</button></template></ElDialog></main></template>
