export const queryKeys = {
  me: ['me'] as const,
  projects: (includeArchived = false) => ['projects', { includeArchived }] as const,
  project: (projectId: string) => ['project', projectId] as const,
  assets: (projectId: string) => ['canon-assets', projectId] as const,
  characters: (projectId: string) => ['characters', projectId] as const,
  worldbook: (projectId: string) => ['worldbook', projectId] as const,
  outlines: (projectId: string) => ['outlines', projectId] as const,
  chapters: (projectId: string) => ['chapters', projectId] as const,
  chapter: (chapterId: string) => ['chapter', chapterId] as const,
  chapterVersions: (chapterId: string) => ['chapter-versions', chapterId] as const,
  workflow: (runId: string) => ['workflow', runId] as const,
  budget: (projectId: string) => ['budget', projectId] as const,
  usage: (projectId: string) => ['usage', projectId] as const,
  costs: (projectId: string) => ['costs', projectId] as const,
  pricingRules: ['pricing-rules'] as const,
  modelConfig: ['model-config'] as const,
  skillComposition: (projectId: string, chapterId: string) => ['skill-composition', projectId, chapterId] as const,
  skills: (projectId: string) => ['skills', projectId] as const,
  globalSkills: ['global-skills'] as const,
  globalSkillVersions: (skillId: string) => ['global-skill-versions', skillId] as const,
  skillBindings: (projectId: string) => ['skill-bindings', projectId] as const,
}
