spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/storyweaver}
    username: ${DB_USERNAME:storyweaver}
    password: ${DB_PASSWORD:storyweaver}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
